apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealldeploy
  labels:
    app: dealldeployapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deall
  template:
    metadata:
      labels:
        app: deall
    spec:
      containers:
        - name: deallimage
          image: docker.io/gerry97/deall:latest
          ports:
            - containerPort: 8800
---
apiVersion: v1
kind: Service
metadata:
  name: dealldeploy
spec:
  type: LoadBalancer
  ports:
    - port: 8800
  selector:
    app:  deall
